spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRESQL_DATABASE_URL:jdbc:postgresql://localhost:5432/cashtrack}
    username: ${POSTGRESQL_DATABASE_USERNAME:postgres}
    password: ${POSTGRESQL_DATABASE_PASSWORD:hgy3pG3zu7o7AIHm}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    driver-class-name: org.postgresql.Driver
    locations: db/migration
    password: ${POSTGRESQL_DATABASE_PASSWORD:hgy3pG3zu7o7AIHm}
    url: ${POSTGRESQL_DATABASE_URL:jdbc:postgresql://localhost:5432/cashtrack}
    user: ${POSTGRESQL_DATABASE_USERNAME:postgres}
#jwt:
#  key: ${JWT_KEY:lsx@LAmH=(aM#c1WJ)ioBWzWJAHSDAz2@1djkwaWQEcasd--123}}
#  access-token-expiration: 3600000 #ms
#  refresh-token-expiration: 86400000 #ms